version: "3"
services:
  postgres:
    image: postgres:15
    container_name: server_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=mitienda
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mitienda_local
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-test:
    image: postgres:15
    restart: always
    container_name: server_postgres_test
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=mitienda_test
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mitienda_local_test

volumes:
  postgres_data:
